apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontned-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: vamckrish08/frontend:2