apiVersion: apps/v1
kind: Deployment
metadata:
  name: own-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: own-users
  template:
    metadata:
      labels:
        app: own-users
    spec:
      containers:
        - name: own-user-container
          image: vamckrish08/user-image:9
          env:
            - name: AUTH_ADDRESS
              value: localhost
        - name: own-auth-container
          image: vamckrish08/auth-image:1
