apiVersion: v1
kind: Service
metadata:
  name: own-user-service
spec:
  selector:
    app: own-users
  type: LoadBalancer
  ports:
    - name: 'user-expose'
      protocol: 'TCP'
      port: 8080
      targetPort: 8080
    - name: 'auth-expose'
      port: 80
      targetPort: 80
