kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eks-host-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08ebf910f3771c882
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eks-host-pvc
spec:
  volumeName: eks-host-pv
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---  
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-api
          image: vamckrish08/eks-user-image:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb://vamckrish:12345678@docdb-2024-11-21-09-22-29.cluster-cf4eg4sk059a.us-east-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false'
            - name: AUTH_API_ADDRESSS
              value: 'auth-service.default:3000'
          volumeMounts:
            - name: efs-vol
              mountPath: /app/users 
      volumes:
        - name: efs-vol
          persistentVolumeClaim:
            claimName: eks-host-pvc

