apiVersion: v1
kind: Service
metadata:
  name: declarative-data-service
spec:
  selector:
    app: data
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 3000
  type: LoadBalancer
